### PR TITLE
[SQL] Support for ASOF join

### PR DESCRIPTION
**Pull request by mihaibudiu**
Is this a user-visible change (yes/no): not yet

### CODE REVIEW

**Comment by mihaibudiu** [comment]
Fixes #2097 
Part of #2009 
Part of #1850 
Fixes #1658

**Comment by blp** [comment]
@mihaibudiu I got a test failure running your script:

```
FAILURE   0.0sec, org.apache.calcite.test.JdbcFrontJdbcBackTest > executionError
    java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
        at java.base/java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2000)
        at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2034)
        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:423)
        at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:162)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:136)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)e:test > 7281 tests completed, 102 skipped
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
```

Also this got printed near the end and I don't know how to interpret it:

```
    Execution failed for task ':core:test':
        java.lang.IllegalArgumentException: Received a completed event for test with unknown id '62.3723'. Registered test ids: '[62.60, 62.50, 62.3123, 62.48, 62.49, 62.36, 62.34, 62.6179, 62.6165, 62.3086, 62.6159, 62.8, 62.5, 62.1, 62.126, 62.127, 62.125, 62.123, 62.116, 62.7285, 62.7283, 62.7278, 62.6244, 62.93, 62.5202, 62.6226, 62.78, 62.6223, 62.6332, 62.178, 62.4275, 62.6316, :core:test, 62.7327, 62.157, 62.5268, 62.6278, 62.6275, 62.7422, 62.7420, 62.7421, 62.7418, 62.7415, 62.7412, 62.7411, 62.239, 62.7404, 62.7405, 62.7401, 62.2276, 62.2275, 62.214, 62.215, 62.4292, 62.7486, 62.7487, 62.7484, 62.7485, 62.7483, 62.7476, 62.7475, 62.7470, 62.7466, 62.7461, 62.7458, 62.7459, 62.7457, 62.7455, 62.7451, 62.7448, 62.7449, 62.7444, 62.7440, 62.7441, 62.7435, 62.7428, 62.7427, 62.7425, 62.5502, 62.7551, 62.5500, 62.7549, 62.7546, 62.4472, 62.7545, 62.7543, 62.7540, 62.7534, 62.7520, 62.7514, 62.6491, 62.7512, 62.7510, 62.7509, 62.7506, 62.3411, 62.7507, 62.6480, 62.7505, 62.7501, 62.7494, 62.7489, 62.7614, 62.7611, 62.7608, 62.3513, 62.5561, 62.7606, 62.7604, 62.3507, 62.7603, 62.6576, 62.7600, 62.7601, 62.7599, 62.7597, 62.6570, 62.424, 62.2468, 62.7584, 62.7582, 62.7580, 62.7578, 62.5524, 62.7572, 62.7571, 62.7566, 62.7567, 62.7560, 62.7559, 62.3461, 62.7553, 62.7677, 62.7675, 62.7672, 62.7673, 62.4598, 62.7671, 62.7668, 62.7667, 62.7665, 62.7662, 62.7663, 62.6637, 62.7661, 62.5611, 62.7659, 62.7656, 62.7657, 62.7655, 62.7652, 62.7653, 62.7650, 62.7648, 62.3550, 62.7646, 62.7644, 62.7642, 62.7643, 62.7638, 62.3543, 62.7639, 62.7632, 62.7633, 62.7630, 62.2511, 62.3535, 62.7631, 62.7629, 62.5578, 62.7626, 62.7625, 62.2503, 62.7620, 62.2499, 62.7742, 62.7740, 62.7741, 62.7738, 62.7736, 62.7737, 62.7734, 62.7735, 62.5684, 62.7732, 62.7733, 62.7731, 62.7729, 62.6702, 62.7726, 62.7725, 62.5672, 62.7721, 62.7718, 62.7716, 62.5666, 62.7712, 62.7710, 62.7711, 62.7708, 62.7709, 62.7707, 62.7705, 62.7702, 62.7703, 62.7700, 62.1557, 62.7698, 62.7699, 62.7697, 62.7694, 62.7695, 62.6668, 62.7692, 62.5645, 62.7691, 62.7688, 62.3593, 62.7689, 62.7687, 62.7684, 62.2565, 62.7685, 62.5632, 62.7680, 62.7806, 62.7807, 62.7804, 62.7802, 62.7803, 62.7801, 62.7798, 62.7796, 62.5749, 62.7790, 62.7791, 62.7789, 62.7786, 62.7784, 62.7785, 62.7780, 62.7781, 62.7777, 62.7774, 62.7773, 62.7770, 62.7768, 62.6740, 62.7763, 62.7760, 62.7758, 62.7759, 62.7756, 62.7757, 62.7754, 62.7750, 62.7748, 62.7746, 62.7747, 62.1600, 62.7744, 62.7870, 62.7871, 62.5820, 62.7868, 62.7866, 62.7867, 62.7864, 62.7865, 62.7862, 62.7863, 62.7861, 62.7858, 62.7859, 62.7856, 62.7857, 62.7854, 62.7855, 62.7852, 62.7850, 62.7851, 62.7848, 62.7849, 62.7846, 62.7847, 62.7844, 62.7845, 62.7842, 62.7843, 62.5793, 62.7841, 62.6814, 62.7839, 62.7836, 62.7837, 62.7835, 62.7831, 62.7828, 62.5781, 62.7829, 62.7826, 62.7827, 62.5776, 62.7825, 62.7822, 62.7823, 62.7820, 62.7821, 62.7818, 62.7819, 62.7816, 62.7817, 62.7812, 62.5765, 62.7813, 62.7811, 62.7808, 62.7809, 62.5884, 62.7926, 62.7927, 62.7924, 62.7922, 62.7923, 62.7920, 62.7921, 62.7918, 62.7916, 62.7917, 62.7914, 62.7912, 62.7910, 62.7908, 62.7907, 62.5856, 62.7904, 62.7905, 62.7902, 62.5853, 62.7901, 62.7899, 62.7896, 62.7897, 62.7894, 62.7895, 62.724, 62.7892, 62.7893, 62.7891, 62.7889, 62.7886, 62.7887, 62.7884, 62.7885, 62.7883, 62.7880, 62.7881, 62.7878, 62.7876, 62.7877, 62.7874, 62.7875, 62.7872, 62.7873, 62.3902, 62.5935, 62.5931, 62.5929, 62.3879, 62.5915, 62.5913, 62.5904, 62.5905, 62.5902, 62.5903, 62.6006, 62.885, 62.3954, 62.6002, 62.5978, 62.5977, 62.5974, 62.853, 62.5970, 62.5968, 62.5966, 62.5964, 62.5963, 62.5961, 62.5959, 62.7086, 62.6048, 62.6040, 62.6016, 62.6136, 62.6107, 62.6090, 62.6089]'
            at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:80)
            at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:60)
            at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
            at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
            at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
            at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
            at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
            at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
            at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
            at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
            at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:51)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
            at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
```

Is there a way to run this thing but skip the tests? I know nothing about gradle or mvn.

**Comment by blp** [comment]
I changed `./gradlew build` to `./gradlew build -x test` and it didn't fail, so I guess that worked.

**Comment by mihaibudiu** [comment]
Fixes #2201

**Pull request merged**
