### PR TITLE
Many UI fixes and improvements, mobile and tablet support

### PR DESCRIPTION
**Pull request by Karakatiza666**
This UI implements most of the latest Web Console design, as well as some minor fixes and improvements

Fix https://github.com/feldera/feldera/issues/2930
Fix https://github.com/feldera/feldera/issues/3102: Improve spacing in ad hoc query results
Fix https://github.com/feldera/feldera/issues/3005: Renaming a running pipeline fails silently

### CODE REVIEW

**Comment by gz** [comment]
let's never move compilation status up there it just looks bad

image

**Comment by gz** [comment]
lets remove the red color here this icon doesn't need to stand out

image

**Comment by gz** [comment]
pressing apply here doesn't do anything (dialog doesn't close)
image

**Comment by gz** [comment]
idk if this is part of the design but this white bar looks kinda ugly

image

it should probably be grey too

**Comment by gz** [comment]
this dialog has a horizontal scroll bar it probably shouldn't have
image

**Comment by gz** [comment]
there is some weird flickering when scrolling the change log 

https://github.com/user-attachments/assets/475919e7-7e84-4bbe-a402-fedc657b0f18

**Comment by gz** [comment]
when you press the three dots button and monitoring tab is hidden it doesn't show up

image

**Review by gz — APPROVED** [review]

**Comment by lalithsuresh** [comment]
The UI doesn't reflect the latest design (positioning of the pipeline status, the save icon, delete background etc). Are all the commits in?

**Comment by Karakatiza666** [comment]
> idk if this is part of the design but this white bar looks kinda ugly

This is the design, it's quick to change it to gray if we decide to

**Comment by Karakatiza666** [comment]
@gz it looks like you haven't successfully compiled the latest commit version, there the delete button is gray and save button is next to configuration button

@lalithsuresh Pipeline Status is over the pipeline name only on smaller screens, I will adjust it so that it's still in one line for screens as wide as on Gerd's screenshot and then merge

**Comment by Karakatiza666** [comment]
An update on pipeline status location: since Documentation and Community Resources dropdowns needed to be added per design, I need to leave plenty of space to render a longer pipeline name. That's why at a certain screen width I move pipeline status over the pipeline name, and leave it there even when Documentation and Community Resources dropdowns eventually get hidden due to restricted width (last screenshot)

image
image
image

**Pull request merged**
