### PR TITLE
[Python] restore the aggregate tests

### PR DESCRIPTION
**Pull request by mihaibudiu**
@rivudhk I hope this reinstates all your changes.

### CODE REVIEW

**Comment by rivudhk** [comment]
@mihaibudiu all my changes are included here.

**Comment by mihaibudiu** [comment]
@rivudhk I have renamed the files and the classes, since Python doesn't like things named with "Test" when there are also unit tests. Our testing does not use the standard unit testing infrastructure, since we don't want to run tests one by one.

**Comment by mihaibudiu** [comment]
@abhizer you don't need to read any of the new tests, just the Earthfile changes

**Review by abhizer — APPROVED** [review]
LGTM, hopefully the CI overlords agree.

**Pull request merged**
