### PR TITLE
Enable nexmark q16; always generate a profile

### PR DESCRIPTION
**Pull request by mihaibudiu**

### CODE REVIEW

**Comment by blp** [comment]
Does this mean that q16 now runs in a reasonable amount of time?

**Comment by mihaibudiu** [comment]
30x faster than it used to, in my local tests
but I don't know if that's fast enough

**Comment by mihaibudiu** [comment]
with 16 workers

**Comment by blp** [comment]
I ran this and it reduced the runtime from frustrating (over an hour?) to about a minute. Sounds great. Thanks!

**Review by blp — APPROVED** [review]

**Pull request merged**
