### PR TITLE
Added memory tracking for Flink

### PR DESCRIPTION
**Pull request by aehmttw**
Is this a user-visible change (yes/no): no

This pull request monitors and logs peak memory utilization for Flink benchmarks.

### CODE REVIEW

**Review by blp — APPROVED** [review]
It would be good to follow up with a refinement that makes sure to only count java processes relaed to Flink, because otherwise we could accidentally capture other processes running on the same system.

**Comment by aehmttw** [comment]
> It would be good to follow up with a refinement that makes sure to only count java processes relaed to Flink, because otherwise we could accidentally capture other processes running on the same system.

At the moment I don't think any Java processes run unless we are benchmarking Flink (or perhaps, benchmarking something else) - do we have plans to ever run multiple benchmarks on a machine in CI at once (in which case stray Java processes would interfere) or will we always only run one task at a time per machine?

**Comment by mihaibudiu** [comment]
Kafka is written in Java too.

**Comment by aehmttw** [comment]
Then that would be a problem when we benchmark Flink with Kafka

**Pull request merged**
