### PR TITLE
Fix working directory for TPC-H benchmarks

### PR DESCRIPTION
**Pull request by mihaibudiu**
Let's see if this fixes the benchmarks CI

### CODE REVIEW

**Comment by gz** [comment]
doesn't look like it passes yet, though it goes a bit further https://github.com/feldera/feldera/actions/runs/10672685814

**Comment by aehmttw** [comment]
Looks like the python environment is missing pandas:
> Traceback (most recent call last):
  File "/dbsp/benchmark/feldera-sql/benchmarks/tpc-h/generate.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by gz** [comment]
@aehmttw do you know which requirements.txt file needs this line added?

**Comment by aehmttw** [comment]
> @aehmttw do you know which requirements.txt file needs a pandas line added?

I'm not entirely sure. The command just uses "python" so I'm not sure if there's a virtual environment set or not. It should run in earthly but I don't see any relevant (associated with benchmark task) requirements.txt there.

**Comment by mihaibudiu** [comment]
Can we merge this to make the CI police happy?

**Comment by gz** [comment]
Getting 

> FileNotFoundError: [Errno 2] No such file or directory: '/dbsp/benchmark/feldera-sql/benchmarks/tpc-h/data-large/customer.csv'

**Comment by mihaibudiu** [comment]
These files are the ones downloaded from https://github.com/dbtoaster/dbtoaster-experiments-data
It looks like they are copied in the wrong directory.

**Comment by gz** [comment]
Do you have a fix for it?

**Comment by mihaibudiu** [comment]
I will try to push another fix, probably just prefix the destination of the move with the current directory

**Comment by gz** [comment]
I don't think tiktok seems to work @aehmttw any ideas what's missing here? I'll disable it for now

```
          +benchmark | 2024-09-04 18:49:48 ERROR [pipeline-0191be5e-6393-75b3-8d05-0fa447315379] Error initializing the pipeline: FATAL error on input endpoint 'interactions.3e88a692ba': failed to subscribe to topics '["interactions"]' (consumer group id '1725475788494'): Message consumption error: UnknownTopicOrPartition (Broker: Unknown topic or partition).
          +benchmark | 2024-09-04 18:49:48 ERROR [pipeline-0191be5e-6393-75b3-8d05-0fa447315379] [HTTP error response] InitializationError: Operation failed because the pipeline failed to initialize. Error details: 'FATAL error on input endpoint 'interactions.3e88a692ba': failed to subscribe to topics '["interactions"]' (consumer group id '1725475788494'): Message consumption error: UnknownTopicOrPartition (Broker: Unknown topic or partition)'.
          +benchmark | 2024-09-04 18:49:48 ERROR [pipeline-0191be5e-6393-75b3-8d05-0fa447315379] Response: 500 Internal Server Error (size: Sized(655)) to request GET /stats
```

**Comment by aehmttw** [comment]
> I don't think tiktok seems to work @aehmttw any ideas what's missing here? I'll disable it for now
Looks like the generator script (generate.bash) didn't run properly and the data is missing from redpanda

**Pull request merged**
