### PR TITLE
[SQL] Introduce syntax to specify connector properties in SQL

### PR DESCRIPTION
**Pull request by mihaibudiu**
Is this a user-visible change (yes/no): yes

### CODE REVIEW

**Comment by mihaibudiu** [comment]
Fixes #1891

**Comment by ryzhyk** [comment]
I don't think we can do multiple sources/sinks per table/view with this. This might be ok.

**Comment by mihaibudiu** [comment]
If you really want multiple sinks you can create additional views.

**Comment by gz** [comment]
What happens with the key-value pairs that are parsed (I didn't find it in the config). FWIW either making them part of the schema file you're already writing out that contains the table meta-data or writing a separate config file for it are both feasible options we can work with.

**Comment by mihaibudiu** [comment]
Look for the json in the tests. The config shows up as another JSON field of the tables and views.

**Comment by mihaibudiu** [comment]
```
connector: {
                 "connector" : "kafka",
                 "url" : "localhost"
               }
```

**Comment by gz** [comment]
found it, cool

**Review by gz — APPROVED** [review]

**Pull request merged**
