### PR TITLE
Add script to run flink on CI

### PR DESCRIPTION
**Pull request by aehmttw**
Is this a user-visible change (yes/no): no

Adds the flink-benchmark Earthly task which runs flink benchmarks and saves the result as flink_results.csv.

The command works as follows:
- installs a newer version of docker compose since the default one doesn't work
- installs maven, which is necessary for flink
- runs flink in docker and pipes the results to run-nexmark.sh, which parses the results into csv format

### CODE REVIEW

**Comment by blp** [comment]
It looks like that script will do what we want. But, yes, we want to invoke it from earthly and get it to install maven beforehand. That's the next step, I guess.

**Review by blp — APPROVED** [review]
Seems good.

How do we get this to run regularly?

**Comment by aehmttw** [comment]
> How do we get this to run regularly?

I can modify the base benchmark's Earthfile to check when the last Flink run was and trigger it if it is older than a certain period of time.

**Comment by blp** [comment]
> > How do we get this to run regularly?
> 
> I can modify the base benchmark in the Earthfile to check when the last Flink run was and trigger it if it is older than a certain period of time.

Sounds good. I think you can merge this PR now, and plan to do that in another one.

**Pull request merged**
