### PR TITLE
dbsp_adapters: Fix problem with file descriptor exhaustion running te…

### PR DESCRIPTION
**Pull request by blp**
…sts.

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]

**Review by gz — COMMENTED** [review]
lgtm I just wondered if a better solution would be to limit the #cores the webserver spawns in tests to a saner number (e.g., 1-2, since we don't have any load tests anyways yet)

**Review by gz — APPROVED** [review]

**Review by ryzhyk — APPROVED** [review]
I wonder if we should also configure actix with a smaller thread pool. But this PR looks good.

**Comment by ryzhyk** [comment]
> lgtm I just wondered if a better solution would be to limit the #cores the webserver spawns on in tests to a saner number (e.g., 1-2, since we don't have any load tests anyways yet)

Not just in tests.  The server only runs the rest API, so there's no point in it using 100 cores.  All the heavy lifting is done by DBSP in its own worker  pool.

**Comment by gz** [comment]
> Not just in tests. The server only runs the rest API, so there's no point in it using 100 cores. All the heavy lifting is done by DBSP in its own worker pool.

agree, the actix default is to spawn as many cores as hyperthreads in the system which seems not a great default (it spawns 128 threads on my machine, I doubt it would scale to that number anyways)

**Review by Kixiron — CHANGES_REQUESTED** [review]
You should gate the ctor and the dependencies to unix platforms, this will break windows contributors

**Comment by ryzhyk** [comment]
> You should gate the ctor and the dependencies to unix platforms, this will break windows contributors

Hmm, I guess this is another reason to actually take a different path and bound the number of actix threads instead.

**Comment by ryzhyk** [comment]
docs: https://actix.rs/docs/server/#multi-threading

**Comment by gz** [comment]
> You should gate the ctor and the dependencies to unix platforms, this will break windows contributors

both dependencies claim to work on windows (no-op)

**Comment by blp** [comment]
> lgtm I just wondered if a better solution would be to limit the #cores the webserver spawns on in tests to a saner number (e.g., 1-2, since we don't have any load tests anyways yet)

I thought that I could do this by setting `TOKIO_WORKER_THREADS=1` in my environment, but that didn't work for me.

**Comment by gz** [comment]
is there anything left with this PR or can we merge @blp ?

**Comment by blp** [comment]
> is there anything left with this PR or can we merge @blp ?

I can't merge it due to @Kixiron 's objection.

It's probably better to use fewer threads in the tests. I'll eventually go back and figure out how to do that.

**Comment by gz** [comment]
>I can't merge it due to @Kixiron 's objection.

See my earlier comment: imo windows should work...

for ctor:
>This library works and is regularly tested on Linux, OSX and Windows, with both +crt-static and -crt-static.

for fd-limit:
>on Windows does nothing

**Comment by Kixiron** [comment]
`ctor`'s not an issue (I just said to gate it because otherwise it would have been an unused dependency) but if `fd-limit` is a noop then I have no objections

**Comment by ryzhyk** [comment]
I still think https://actix.rs/docs/server/#multi-threading is the way to go.

**Comment by gz** [comment]
Even if we reduce threads, it's still a good idea to raise the max limit of fds. It's just a dumb setting that only causes confusion for end  users and hard to understand  errors. 

So far I ran into this on the manager, but also on the pipeline itself (when running with rocksdb), and redpanda also failed on me because of it.

**Comment by blp** [comment]
I'll revisit this next weekl.

**Comment by ryzhyk** [comment]
Since the fix amounted to uncommenting my own line of code, I submitted a fix: #757.
I'm ok with merging this one too as suggested by @gz

**Comment by mihaibudiu** [comment]
So let's merge this.

**Comment by blp** [comment]
I think I'm going to just drop this PR, because otherwise we're running our tests with a fdlimit of 65535 but in production we have no such protection, and, like, 3 years from now, that's going to cause mysterious undebuggable problems.

It's better to fix it by limiting threads, as @ryzhyk has already done. If that doesn't avoid the problem, then, we can revisit it.

**Comment by gz** [comment]
FWIW I'm not sure if the thread fix ever got merged? I'm still running into the too many open fds

```
thread 'actix-server worker 127' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /home/gz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.3.0/src/worker.rs:404:34
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: actix_server::worker::ServerWorker::start::{{closure}}
             at /home/gz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.3.0/src/worker.rs:400:38
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: actix_server::worker::ServerWorker::start::{{closure}}
             at /home/gz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.3.0/src/worker.rs:400:38
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: actix_server::worker::ServerWorker::start::{{closure}}
             at /home/gz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.3.0/src/worker.rs:400:38
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: actix_server::worker::ServerWorker::start::{{closure}}
             at /home/gz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.3.0/src/worker.rs:400:38
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
^C2023-10-17 15:09:01 INFO [manager] SIGINT received; starting forced shutdown
2023-10-17 15:09:01 INFO [manager] accept thread stopped
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] SIGINT received; starting forced shutdown
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] accept thread stopped
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:01 INFO [manager] shutting down idle worker
2023-10-17 15:09:02 INFO [manager] waiting for server to shut down.... done
2023-10-17 15:09:02 INFO [manager] server stopped
```

**Comment by ryzhyk** [comment]
Interesting.  The fix was merged, but it only limits the number of workers in the pipeline, not the manager.  We should apply the same fix to the manager.

**Pull request closed without merging**
