### PR TITLE
[SQL] NULL values for columns with LATENESS are never considered late

### LINKED ISSUE #2517: NULL-able column with LATENESS drops inputs.
I think this has come up before, but I don't see an issue for this. Given the following program:

```sql
CREATE TABLE transaction (
    ts TIMESTAMP LATENESS INTERVAL 1 DAYS,
    amt DOUBLE,
    customer_id BIGINT NOT NULL, 
    state VARCHAR
) with ('materialized' = 'true');

CREATE MATERIALIZED VIEW red_transactions AS
SELECT
    *
FROM
    transaction;
```

I insert a record with the timestamp field set to `NULL`.

```sql
insert into transaction values (NULL, 4.0, 2, 'CA');
```

The record appears on the `transaction` table, but not in the view:

```
localhost:8080/bug2> select * from transaction;

+----+-----+-------------+-------+
| ts | amt | customer_id | state |
+----+-----+-------------+-------+
|    | 4.0 | 2           | CA    |
+----+-----+-------------+-------+

localhost:8080/bug2> select * from red_transactions;

+----+-----+-------------+-------+
| ts | amt | customer_id | state |
+----+-----+-------------+-------+
+----+-----+-------------+-------+
```

But when I insert another record with `ts = NULL`, it does show up in the view:

```
localhost:8080/bug2> insert into transaction values (NULL, 5.0, 2, 'CA');

+-------+
| count |
+-------+
| 1     |
+-------+

localhost:8080/bug2> select * from red_transactions;

+----+-----+-------------+-------+
| ts | amt | customer_id | state |
+----+-----+-------------+-------+
|    | 5.0 | 2           | CA    |
+----+-----+-------------+-------+
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #2517

### CODE REVIEW

**Review by ryzhyk — CHANGES_REQUESTED** [review]
I am not sure that storing NULL timestamps forever is the right approach.

**Comment by mihaibudiu** [comment]
What do you suggest?

**Comment by mihaibudiu** [comment]
Either the type is not null, and then it's clear what to do. If the type is nullable it means that null timestamps are expected. And then it means they have to be processed. Whether they are kept forever depends on what else the program does to them.

**Comment by mihaibudiu** [comment]
@ryzhyk I don't think we can do any better than this, can you please approve this so we can merge it?

**Review by ryzhyk — APPROVED** [review]

**Pull request merged**
