### PR TITLE
pipeline-manager: snippet field in SQL compiler message

### PR DESCRIPTION
**Pull request by snkas**
Is this a user-visible change (yes/no): no

### CODE REVIEW

**Comment by snkas** [comment]
Integrates the `snippet` field provided by the compiler.
* Related to issue https://github.com/feldera/feldera/issues/1842
* Successor to PR https://github.com/feldera/feldera/pull/1847

To check it works:
```python
from feldera import FelderaClient, SQLContext
client = FelderaClient("http://localhost:8080")
sql = SQLContext("reproduce", client).get_or_create()
sql.register_view("example_view", "SELECT COUNT(*) FROM example_table")
sql.run_to_completion()
```

**Comment by snkas** [comment]
What was the original SQL used in the example of the doc? Then I can add the appropriate snippet rather than "...".

**Comment by mihaibudiu** [comment]
> What was the original SQL used in the example of the doc? Then I can add the appropriate snippet rather than "...".

who is supposed to answer this question?

**Comment by mihaibudiu** [comment]
why aren't you using your own example in this PR?

**Review by mihaibudiu — APPROVED** [review]

**Comment by snkas** [comment]
True, I'll just edit to own example and merge it :+1:

**Comment by snkas** [comment]
Done in the rework API PR by @Karakatiza666 .

**Pull request closed without merging**
