### PR TITLE
Experimental Snowflake sink.

### PR DESCRIPTION
**Pull request by ryzhyk**
We use the Snowflake Kafka connector with Snowpipe Streaming to send a stream of output changes from Feldera into Snowflake.  The main challenge is that Snowpipe currently supports inserts but not updates or deletions.  The workaround is to write all updates into a set of landing tables that mirror the target database schema and use a combination of snowflake streams to incrementally apply these updates to target tables by converting them into insert/update/delete commands.

So the end-to-end process is:

* Feldera outputs updates to Kafka
* The Snowflake Kafka connector converts them into a stream of inserts into landing tables.
* We attach a Snowpipe Stream to each landing table to track changes to the table.  A periodic task reads updates from the stream, applies them to the target table and removes them from the landing tables.

At the moment the landing tables and the data ingestion logic (Snowflake streams and tasks) must be written by the user, but they can in principle be automatically generated.

TODO:
- Docs (https://github.com/feldera/feldera/issues/867)
- WebConsole support (https://github.com/feldera/feldera/issues/859)
- Support Snowflake's `TIMESTAMP` format (https://github.com/feldera/feldera/issues/862)
- Figure out how to apply multiple updates atomically (See: https://github.com/snowflakedb/snowflake-kafka-connector/issues/717)
- Test under load.
- Automate the generation of landing tables and data ingestion tasks.
- Figure out downtime and schema evolution ops.

Addresses https://github.com/feldera/feldera/issues/774

Is this a user-visible change (yes/no):  yes

cc @mohsinbeg

### CODE REVIEW

**Comment by mihaibudiu** [comment]
So everything is streaming but this last step is batch. They ruin everything.

**Comment by ryzhyk** [comment]
> So everything is streaming but this last step is batch. They ruin everything.

Microbatch, but yeah...  It's possible to trigger the task more frequently from outside of Snowflake.  This is what I do to run the test quickly in CI.

**Comment by gz** [comment]
> The main challenge is that Snowpipe currently supports inserts but not updates or deletions. The workaround is to write all updates into a set of landing tables


How do we ensure that insert -> delete -> insert (same pkey) does not get reordered to insert -> insert (fail because already exists) -> delete

**Comment by ryzhyk** [comment]
> > The main challenge is that Snowpipe currently supports inserts but not updates or deletions. The workaround is to write all updates into a set of landing tables
> 
> How do we ensure that insert -> delete -> insert (same pkey) does not get reordered to insert -> insert (fail because already exists) -> delete
> 
> (more general how to ensure consistency between landing tables and inserts from snowpipe)

We do this by identifying and applying the last update for the given record or,for a table with a pkey, for the given key.

**Review by lalithsuresh — APPROVED** [review]

**Pull request merged**
