### PR TITLE
[WebConsole] Add Ad-hoc query UI

### PR DESCRIPTION
**Pull request by Karakatiza666**
The PR also updates versions of a lot of dependencies

Fix https://github.com/feldera/feldera/issues/2504

### CODE REVIEW

**Comment by Karakatiza666** [comment]
image
image

**Comment by gz** [comment]
I tried to run this query,  but nothing happens

https://github.com/user-attachments/assets/afc4482d-a58e-4f8e-bb6b-6439ba0e9b8b

please make sure it's well tested

**Comment by gz** [comment]
image

I think this should look the same (height wise) as the warning bar we have when records get dropped

**Comment by gz** [comment]
Please separate the update dependencies and ad-hoc queries into two separate commits. Last time this introduced a bunch of bugs.

**Comment by Karakatiza666** [comment]
Will need help reproducing your issue

**Comment by Karakatiza666** [comment]
image
image

**Comment by gz** [comment]
Hi lgtm!

I'd just make this an INFO level color since it's not an error

Screenshot from 2024-09-27 07-55-20

also we seem to be using two different "layouts" for errors the compiler errors have red font and here there is a red background? Any idea why? maybe we can use the same layout for both

**Comment by gz** [comment]
Can prompt be hidden when pipeline is not running?

image

Array objects don't work make sure to test with all types

image

Don't add new prompt until there is a successful query (e.g., have seen some data -- note some queries may display and fail later in this case new prompt is fine)

image

Make these the same (height/font size etc.)
image
image

**Comment by Karakatiza666** [comment]
I suggest to work on displaying non-trivial value types in a separate PR - I would first like to use the same UI elements for change stream and adhoc UI tables, and then introduce custom rendering for each non-trivial type

**Comment by gz** [comment]
You dont need to do custom rendering but afaict the table view breaks when you have arrays in the mix (eg the other cols are empty)

**Comment by lalithsuresh** [comment]
> I suggest to work on displaying non-trivial value types in a separate PR - I would first like to use the same UI elements for change stream and adhoc UI tables, and then introduce custom rendering for each non-trivial type

It's okay if change stream looks different for now. Better to harden ad-hoc UI first.

**Review by gz — APPROVED** [review]

**Pull request merged**
