### PR TITLE
demo: product-availability

### PR DESCRIPTION
**Pull request by snkas**
Is this a user-visible change (yes/no): no

### CODE REVIEW

**Comment by mohsinbeg** [comment]
Lets have a SQL model that uses multiple tables with continuous upsert and delete doing `over`, `top K`, `cross apply` queries.

**Comment by snkas** [comment]
Updated the SQL model and corresponding data generation

**Review by lalithsuresh — APPROVED** [review]
I don't see any code that issues row deletes to the pipeline. Is it the case that there will be only a fixed number of rows, which are continuously updated?

**Comment by snkas** [comment]
Yes, the current version is only with upserts. After this first continuous demo, I think we can expand the range and create another demo that does row deletes to limit input table size.

**Comment by snkas** [comment]
Rebased against main, updated URL in README, couple of Python comment script updates.
Awaiting CI to merge.

**Comment by snkas** [comment]
Added data generation status update at T=1, 6, 11, 16, etc. instead of after every row

**Pull request merged**
