### PR TITLE
Replace paper links with some more persistent links

### PR DESCRIPTION
**Pull request by mihaibudiu**

### CODE REVIEW

**Comment by mihaibudiu** [comment]
Fixes #722

**Comment by ryzhyk** [comment]
What's wrong with https://www.feldera.com/vldb23.pdf?

**Comment by mihaibudiu** [comment]
Is the paper there?

**Comment by ryzhyk** [comment]
yep

**Comment by mihaibudiu** [comment]
I will merge this, the links have been broken long enough.

**Pull request merged**
