### PR TITLE
White space in date and time types

### PR DESCRIPTION
**Pull request by blp**

### CODE REVIEW

**Review by ryzhyk — CHANGES_REQUESTED** [review]
This doesn't fix the Rust deserialization code in `timestamp.rs` required to address the issue. @blp , your your original fix (https://github.com/feldera/feldera/commit/0fa31b7ebcdc005755202151db77b48610dc8a43) actually contained the necessary changes to  `timestamp.rs`.

**Comment by blp** [comment]
> This doesn't fix the Rust deserialization code in `timestamp.rs` required to address the issue. @blp , your your original fix ([0fa31b7](https://github.com/feldera/feldera/commit/0fa31b7ebcdc005755202151db77b48610dc8a43)) actually contained the necessary changes to `timestamp.rs`.

Hmm, @mihaibudiu wanted me to drop all the changes to that file: https://github.com/feldera/feldera/issues/443#issuecomment-1707443967.

I'm just confused now about who wants what.

**Comment by ryzhyk** [comment]
Sorry about the confusion.  I'm not sure why he'd want to revert these changes.

**Comment by mihaibudiu** [comment]
Unfortunately the CI seems broken completely, so we can't rely on it to validate this change.
We cannot change the rules for literals that appear in SQL code. And date literals are in fact string literals with a cast.

**Comment by ryzhyk** [comment]
@blp , I'll take over this PR if you don't mind.  I'll bring back your change to `timestamp.rs` and add an integration test for it.

**Comment by mihaibudiu** [comment]
Indeed, the main problem is that we don't have tests for serialization.
At least the compiler doesn't.
It looks like the timestamp.rs changes were correct too.

**Comment by blp** [comment]
> @blp , I'll take over this PR if you don't mind. I'll bring back your change to `timestamp.rs` and add an integration test for it.

Thank you!

**Review by ryzhyk — APPROVED** [review]

**Pull request merged**
