### PR TITLE
dbsp: Reduce memory use for merges with output smaller than the inputs.

### PR DESCRIPTION
**Pull request by blp**
Is this a user-visible change (yes/no): no

### CODE REVIEW

**Comment by blp** [comment]
Finally passed CI, argh.

**Comment by lalithsuresh** [comment]
@blp is this good to merge?

**Comment by blp** [comment]
Yes, it's ready. I don't know whether Leonid wants to look at it first.

**Review by ryzhyk — APPROVED** [review]
Sorry about the delay. I was sure I'd reviewed this already. @blp , any idea if this has any measurable impact on performance?

**Comment by blp** [comment]
I didn't see an impact on performance in my tests. I only ran a few.

**Pull request merged**
