### PR TITLE
Make sure dockerfile is correct

### PR DESCRIPTION
**Pull request by gz**
e.g., passes
docker build -f deploy/Dockerfile --target release .

### CODE REVIEW

**Comment by gz** [comment]
Tried to add a test with FROM DOCKERFILE to earthly but couldn't get it to work yet.. also realized that it needs everything as dependency so it will run this also pretty much every time and prolong CI so not sure it's a good idea anymore ... would be great to be able to tell earthly "only this file is relevant for deciding whether something should re-run, ignore all the other deps"

**Review by lalithsuresh — APPROVED** [review]

**Comment by lalithsuresh** [comment]
> also realized that it needs everything as dependency

Not sure I follow. What dependencies does it need?

**Comment by gz** [comment]
all of the repo code .. eg every time compiler or pipeline manager etc changes the dockerfile test will run again .. might be ok but I really only like to test the dockerfile with this so ideally I would be able to express "inly run this test if Dockerfile has chnaged"...

**Comment by lalithsuresh** [comment]
@gz You could try doing it manually

```
test-dockerfile:
   FROM earthly/dind:alpine
   COPY deploy/Dockerfile . # caching happens here
   WITH DOCKER
        RUN docker build blahblah
   END
```

**Pull request merged**
