### PR TITLE
Multiple WebConsole fixes and improvements

### PR DESCRIPTION
**Pull request by Karakatiza666**
Hide drawer when WebConsole is first opened on mobile
Make SQL value popup appear on click instead of on hover in data tables
Make numbers right-aligned in data tables, add truncation of insignificant decimal digits
Display 'create new pipeline' button on home page above demos on mobile
Reduce right padding of file tabs so that they fit on mobile in one line
Use virtual list for better performance of Ad-hoc query results table
Improve scrollbar on examples page
Spell 'Insert' and 'Delete' instead of '+' and '-' in Change Stream
Other minor fixes

image
image
image

### CODE REVIEW

**Comment by Karakatiza666** [comment]
Numbers are now right-aligned:
image

Ad-hoc query results now stick to bottom:
image

SQL Value popup now only appears on click

**Comment by Karakatiza666** [comment]
image
image
image

**Comment by gz** [comment]
> Spell 'Insert' and 'Delete' instead of '+' and '-' in Change Stream

why this change?

**Review by gz — APPROVED** [review]

**Comment by Karakatiza666** [comment]
Right now the entire left column's width is taken up by a table name, so I decided since the space is wasted anyway I might as well spell out the event type. Leonid approves.
If I manage to display table name over column names as a second row I will revert to '+' and '-' to save space

**Pull request merged**
