### PR TITLE
Add Swagger link to navbar, make navbar more compact

### PR DESCRIPTION
**Pull request by Karakatiza666**
Is this a user-visible change (yes/no): yes

Fix https://github.com/feldera/feldera/issues/1403

The link is added to navbar because for now it is used instead of an actual page footer
image

### CODE REVIEW

**Comment by mihaibudiu** [comment]
what is swagger?

**Comment by Karakatiza666** [comment]
It is a widely used system to auto generate docs and interactive examples to APIs. @mohsinbeg should the link have a more descriptive name, e.g. "Swagger Docs" ?

**Comment by gz** [comment]
lgtm, while you're changing the navbar maybe you can remove the demo and settings link if they lead to an empty page?

**Comment by Karakatiza666** [comment]
@gz that's a dynamic logic I plan to do in a separate PR

**Pull request merged**
