### PR TITLE
[SQL] Preliminary support for MAP types

### PR DESCRIPTION
**Pull request by mihaibudiu**
Is this a user-visible change (yes/no): yes

MAP types have been on the wishlist for a long time.
They are also an important stepping stone for properly supporting JSON.
JSON objects are really `MAP<VARCHAR, VARIANT>` values.

### CODE REVIEW

**Comment by ryzhyk** [comment]
What's included in preliminary support?

**Comment by mihaibudiu** [comment]
The documentation describes the new additions: 
- syntax for MAP types `MAP<INT, VARCHAR>` (terrible choice, different from all other types so far, but inherited from Calcite)
- syntax for MAP literals `MAP['a', 1, 'b', 2]`
- syntax for indexing in maps `m['a']`

To be followed by many utility functions

**Comment by ryzhyk** [comment]
We should test (de)serializing map values

**Comment by mihaibudiu** [comment]
I will merge this before we test de/serialization. It's still useful for internal tables.

**Pull request merged**
