### PR TITLE
Send attributes that are null as part of JSON response.

### LINKED ISSUE #2839: [WebConsole] The AdHoc query tab doesn't handle empty columns correctly
Here is the output of the same query in fda vs webconsole:

```
localhost:8080/lateness> select * from purchase_with_prev_next order by ts;

+---------------------+-------------+--------+-----------------+-------------+
| ts                  | customer_id | amount | previous_amount | next_amount |
+---------------------+-------------+--------+-----------------+-------------+
| 2020-01-01T01:00:00 | 1           | 10     |                 | 10          |
| 2020-01-01T02:00:00 | 1           | 10     | 10              | 20          |
| 2020-01-01T03:00:00 | 1           | 20     | 10              | 11          |
| 2020-01-01T03:15:00 | 1           | 11     | 20              | 50          |
| 2020-01-01T03:30:00 | 1           | 50     | 11              |             |
+---------------------+-------------+--------+-----------------+-------------+
```

image

This is what JSON looks like:

```json
{"ts":"2020-01-01T01:00:00","customer_id":1,"amount":10,"next_amount":10}
{"ts":"2020-01-01T02:00:00","customer_id":1,"amount":10,"previous_amount":10,"next_amount":20}
{"ts":"2020-01-01T03:00:00","customer_id":1,"amount":20,"previous_amount":10,"next_amount":11}
{"ts":"2020-01-01T03:15:00","customer_id":1,"amount":11,"previous_amount":20,"next_amount":50}
{"ts":"2020-01-01T03:30:00","customer_id":1,"amount":50,"previous_amount":11}
```

Looks like we need to include missing fields with `null` values if we want to give webconsole a chance to interpret the rows correctly

### PR DESCRIPTION
**Pull request by gz**
Otherwise it's hard for clients to figure out which fields a query returns.

Fixes #2839

### CODE REVIEW

**Comment by gz** [comment]
@Karakatiza666 I tried some basic tables with the web-console and they seem to work now, but maybe you can do some more extensive testing and check it works with the code in the UI.

**Review by mihaibudiu — APPROVED** [review]

**Review by ryzhyk — APPROVED** [review]
works for me. There's a slight inconsistency: WebConsole shows `null` for NULL cells, whereas fda leaves them empty.

**Comment by snkas** [comment]
I'd advocate for showing upper case `NULL` in the display of both Web Console and fda

**Comment by Karakatiza666** [comment]
In WebConsole I'll show it as _NULL_ to disambiguate from a string

**Review by Karakatiza666 — APPROVED** [review]
I made a change to visually disambiguate null from a string in a separate PR

**Pull request merged**
