### PR TITLE
pipeline-manager: pipeline API logs stub

### PR DESCRIPTION
**Pull request by snkas**

### CODE REVIEW

**Review by gz — APPROVED** [review]

**Review by ryzhyk — COMMENTED** [review]
Do you envisage using this API to stream logs or just to download them as a bundle? In the former case, should we allow "tailing" the log, e.g., send the last N records and then keep sending new records.

**Comment by gz** [comment]
we could also put logs in a "system table" now using the batchsql

**Comment by mihaibudiu** [comment]
Everything should be a table or view. But what to do if they grow too much?

**Comment by gz** [comment]
seems like a bad design to store logs about a thing in the thing itself

**Comment by gz** [comment]
It looks like we need an RFC.

**Comment by ryzhyk** [comment]
> seems like a bad design to store logs about a thing in the thing itself

yes, the other thing should be somehow isolated. Having said this, the goal here is:

1. Have a mechanism to capture logs
2. Expose them to the user

Let's do this in the simplest way possible and worry about fancy incremental log analysis later. I am ok with the overall approach in this PR and think we should finish it.

**Comment by snkas** [comment]
I envision that it is indeed streaming, with new logs coming in. I think it would be the best if the runner is responsible for retrieving the logs from whichever run method it has (e.g., locally the process, or Kubernetes in the cloud). Hence I think option (1) of https://github.com/feldera/feldera/issues/2407 is likely best option for the first implementation, and also relatively simple. What other aspects would you like to see/discussed in an RFC?

It should also be an implementation detail to the user, the logs endpoint of the API server should be the only user-facing component.

**Comment by ryzhyk** [comment]
> What other aspects would you like to see/discussed in an RFC?

Do we need a way to control the offset in the log that the endpoint will start streaming from? If it streams the entire log from the beginning every time, there can potentially be millions of entries, e.g., due to many parsing errors or verbose log level.

**Comment by gz** [comment]
I think we could re-use almost all code by exposing this as a table in the adhoc engine.

- no new code/endpoint needed, will stream results
- getting last lines becomes e.g., `select line from logs order by time desc`
- apply more complex filtering (level=error blabla) etc. directly on the server side

**Comment by snkas** [comment]
Isn't by having the logs be produced by the application itself it will never contain panics, out-of-memory, and crashes in general?

**Comment by lalithsuresh** [comment]
For now, I suggest doing the quick option of having the runner expose a log endpoint.  I would not use system tables to share logs.

If you go the system table route, it should instead be hosting a series of "events" instead, and internally the pipeline should emit events to this table. If you want some inspiration, Kubernetes does this brilliantly.

**Comment by lalithsuresh** [comment]
My understanding was adding support for system tables is a lot of work for Leonid and Mihai (at least the last time this came up). 

As Simon said, the local runner can cat/tail the pipeline logs and the cloud runner can use the k8s logs api.

**Comment by gz** [comment]
> Isn't by having the logs be produced by the application itself it will never contain panics, out-of-memory, and crashes in general?

so in the separate endpoint case this endpoint only lives in the pipeline manager? and it gets the logs for the pipeline not from the pipeline itself?

**Comment by gz** [comment]
> My understanding was adding support for system tables is a lot of work for Leonid and Mihai (at least the last time this came up).

It's very easy to make it an adhoc table, no need for dbsp circuitry

**Comment by snkas** [comment]
Yes, from following the command stdout/stderr in local-runner or using the API equivalent of `kubectl logs` for k8s.

**Comment by gz** [comment]
>Yes, from following the command stdout/stderr in local-runner or using the API equivalent of kubectl logs for k8s.

I see this is the more robust option then, I like it

**Comment by snkas** [comment]
I'll implement a version for local-runner starting tomorrow, hopefully will already have something to show by end-of-day

**Pull request closed without merging**
