### PR TITLE
pipeline-manager: restrict maximum length and pattern of names

### PR DESCRIPTION
**Pull request by snkas**
Name must now, besides being non-empty, also be at most 100 characters long and contain only characters which are lowercase (a-z), uppercase (A-Z), numbers (0-9), underscores (_) or hyphens (-).

This naming restriction applies to:
- Pipeline name
- API key name
- Connector name

Is this a user-visible change (yes/no): yes

### CODE REVIEW

**Comment by snkas** [comment]
I've kept the restriction on the names expressly general (only characters that are allowed, not specific patterns like not allowing starting with a hyphen or underscore). It can potentially be changed to be more restrictive in future, but thought it would already be an improvement to limit to a certain extent (e.g., no spaces anymore).

**Comment by Karakatiza666** [comment]
I will add client-side validation for webconsole either in this PR tomorrow, or separately if merged today. Approving as is now

**Review by Karakatiza666 — APPROVED** [review]

**Comment by gz** [comment]
what happens if someone upgrades to this code and has a non-conform name in his db already?

**Comment by snkas** [comment]
The check happens when the pipeline is created or updated, the API key is created, or the SQL is recompiled. Existing names will continue to work.

**Pull request merged**
