### PR TITLE
Benchmark

### PR DESCRIPTION
**Pull request by blp**
We'd like to be able to graph speed, memory, and CPU consumption for Flink and Feldera. This series makes that possible.

Is this a user-visible change (yes/no): no

### CODE REVIEW

**Comment by aehmttw** [comment]
I triggered a run of this for Flink so we can see if everything works in CI: https://github.com/feldera/feldera/actions/runs/10276370997

**Comment by blp** [comment]
Good idea, thanks! It worked ok locally in Earthly but you never know....

**Comment by blp** [comment]
That's odd! What's the command line?

**Comment by blp** [comment]
> I'm not sure if this is an issue with something being out of date on my machine, but I get this error when I try to run "run.py" as directed by the readme for benchmarking feldera-sql:
> 
> ```
> Stopping pipeline(s)...
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
>     response.begin()
>   File "/usr/lib/python3.10/http/client.py", line 318, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> ```

I get an error like that if I don't have the pipeline manager running.

**Pull request merged**
