### PR TITLE
ci: add basic multiarch build

### PR DESCRIPTION
**Pull request by no2chem**
This PR adds a basic multiarch build, modifying the `containers.yml` pipeline to build both linux/amd64 and linux/arm64 images using buildx.

QEMU is used to perform the multiarch build on arm64, since Github runners don't support CI yet. This could be potentially slow. If it is, we could modify the Dockerfile to use $TARGETARCH vars and direct the compilers to cross-compile instead.

### CODE REVIEW

**Comment by lalithsuresh** [comment]
Could you attempt a build and let us know how fast it runs? Last time I tried it it was painfully slow but I didn't spend much time on it either.

**Comment by no2chem** [comment]
Hm, if you think it's going to be painfully slow I can take a few minutes to modify the dockerfile to cross-compile instead. I know rustc is definitely slow in qemu.

**Comment by lalithsuresh** [comment]
What I recall trying was using `docker buildx with --platform linux/amd64,linux/aarch64`, which is what I think the CI configuration you shared would do. I ran it on Apple Silicon, so maybe this runs better on x86.

**Comment by no2chem** [comment]
Yeah more or less. I added multiarch to the dockerfile so hopefully it works, just running it locally, will let you know if it works after I come back from lunch

Also, node 19.x I guess is deprecated, it causes a 60 second wait displaying a warning, might be worth updating it to 20 if it doesn't break anything for you.

**Comment by no2chem** [comment]
Okay, I added a cross compiling dockerfile which seems to work. I don't know how long it'll add to your build pipeline because I can't run it, but it appears to complete in a reasonable amount of time for me locally.

**Pull request closed without merging**
