### PR TITLE
[WebConsole] Hide UDF tabs if the pipeline doesn't have UDFs until the user wants one

### PR DESCRIPTION
**Pull request by Karakatiza666**
image

### CODE REVIEW

**Comment by ryzhyk** [comment]
* Does this make sure that the tabs are visible if there is some code in udf.rs or udf.toml?
* How is the user's choice stored?

**Comment by Karakatiza666** [comment]
The user's choice is stored until a browser refresh
In this commit I am only checking for content in udf.rs, I will also check for anything in udf.toml

**Comment by ryzhyk** [comment]
So if there's anything in at least one of those files, the three extra tabs will always be visible. Otherwise, they hide automatically after reload.  That makes sense to me.

**Comment by lalithsuresh** [comment]
Something simple to show/hide UDF tabs might be sufficient and less error prone if it's easy to do.

With your change, I'd be worried about the surface area for bugs:
* Does it correctly display the tabs if the are UDFs are created via API while the browser is open?
* What happens if the user adds UDFs and then deletes them via API.
* What happens if create function is defined in the SQL but udf.rs or udf.toml are unchanged?

**Comment by Karakatiza666** [comment]
> Does it correctly display the tabs if the are UDFs are created via API while the browser is open?

Yes
> What happens if the user adds UDFs and then deletes them via API.

Until a page reload - all tabs will be shown, after the reload back to "+ Add UDF"
> What happens if create function is used in the SQL but udf.rs or udf.toml are unchanged?

You would still have to click "+ Add UDF", seems like a really minor inconvenience

**Comment by ryzhyk** [comment]
> You would still have to click "+ Add UDF", seems like a really minor inconvenience

We could also use the contents of stubs.toml to decide whether to expand the tabs.

**Comment by Karakatiza666** [comment]
Basically, if there is `pub fn` declaration?

**Comment by Karakatiza666** [comment]
Additionally, I need to work on the behavior where you had e.g. udf.rs tab open when you removed any udf content via API (user needs to be redirected to program.sql)
Since this is a rare corner case I could create an issue and work on this later...

**Comment by ryzhyk** [comment]
> Basically, if there is `pub fn` declaration?

I was thinking of using the line count, but this is probably better.

**Comment by lalithsuresh** [comment]
I still vote that we'll get most of the value and fewer corner cases from just a show-hide UDFs button. :)

**Comment by ryzhyk** [comment]
> I still vote that we'll get most of the value and fewer corner cases from just a show-hide UDFs button.

Show/hide is definitely a better name for that button. My only concern is the first-time experience adding a UDF declaration and not knowing where to put the Rust code.

**Comment by Karakatiza666** [comment]
> I still vote that we'll get most of the value and fewer corner cases from just a show-hide UDFs button. :)

Do you mean the code wouldn't check if there is any UDF-related code, and just hide UDF tabs by default?

**Comment by ryzhyk** [comment]
> Additionally, I need to work on the behavior where you had e.g. udf.rs tab open when you removed any udf content via API (user needs to be redirected to program.sql) Since this is a rare corner case I could create an issue and work on this later...

I don't think we want to collapse open tabs automatically.  Once it's open, it can remain open.  Let's keep it simple.

**Comment by lalithsuresh** [comment]
> Do you mean WebConsole wouldn't check if there is any UDF-related code, and just hide UDF tabs by default?

Yes. No automatic and fancy checks. Just a show-hide UDFs arrow/button (or whatever is intuitive) that makes the tabs visible or not.

**Comment by lalithsuresh** [comment]
E.g.


Example:
```
# default (UDFs hidden), the > is a button or a burger icon (which we already use to expand/collapse the side bar)
| program.sql | UDFs >


# UDFs shown, after clicking >.
| program.sql | stub.rs | udf.rs | udf.toml  < Hide UDFs
```

**Comment by Karakatiza666** [comment]
Should this Show/Hide button take effect per pipeline or for all pipelines?

**Comment by lalithsuresh** [comment]
Whichever option is more convenient and less error prone (maybe make it global?).

**Comment by Karakatiza666** [comment]
Both are easy and safe

**Comment by Karakatiza666** [comment]
I don't like this solution, but here we go
image
image

Hidden by default for all pipelines, choice reset on page reload

And I still need to redirect to `program.sql` if user "Hides UDF" while on `udf.rs`
I'd rather handle the same case with "Add UDF" version

**Comment by Karakatiza666** [comment]
This is a simple and orthogonal feature, so I don't believe "error-proneness" should be considered when determining the desired UX

**Comment by gz** [comment]
I don't think this is a good change, reason being we're doing something I've never seen any other code editor/UI do. I vote we keep the current behavior.

**Pull request closed without merging**
