### PR TITLE
[SQL] support for tables with primary keys in JIT

### PR DESCRIPTION
**Pull request by mihaibudiu**
Is this a user-visible change (yes/no): no

The corresponding new test is disabled waiting for #890

### CODE REVIEW

**Comment by mihaibudiu** [comment]
The CI failure is this:
```
Running test: "tests/sql_tests/supply_chain"
      +test-adapters *failed* | thread 'supply_chain_test' panicked at crates/adapters/tests/jit_integration_test.rs:30:5:
      +test-adapters *failed* | assertion failed: Command::new(\"../../../../../sql-to-dbsp-compiler/SQL-compiler/sql-to-dbsp\").current_dir(test_dir).args([\"-js\",\n                                \"schema.json\", \"-i\", \"-j\", \"--alltables\",\n                                \"project.sql\"]).stdout(ir_file).output().unwrap().status.success()
```

But I don't know if it's related to the changes in this PR.

**Comment by ryzhyk** [comment]
The error comes from the SQL compiler:

```
cd crates/adapters/tests/sql_tests/supply_chain
../../../../../sql-to-dbsp-compiler/SQL-compiler/sql-to-dbsp  -js schema.json -i -j --alltables project.sql 
```

throws
```
Exception in thread "main" org.dbsp.sqlCompiler.compiler.errors.InternalCompilerError: Circuit contains an integration operator
	at org.dbsp.sqlCompiler.compiler.visitors.outer.NoIntegralVisitor.preorder(NoIntegralVisitor.java:43)
	at org.dbsp.sqlCompiler.circuit.operator.DBSPIntegralOperator.accept(DBSPIntegralOperator.java:38)
	at org.dbsp.sqlCompiler.circuit.DBSPPartialCircuit.accept(DBSPPartialCircuit.java:111)
	at org.dbsp.sqlCompiler.circuit.DBSPCircuit.accept(DBSPCircuit.java:61)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.apply(CircuitVisitor.java:76)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.apply(CircuitVisitor.java:40)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.Passes.apply(Passes.java:73)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.Passes.apply(Passes.java:36)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitOptimizer.optimize(CircuitOptimizer.java:79)
	at org.dbsp.sqlCompiler.compiler.DBSPCompiler.optimize(DBSPCompiler.java:347)
	at org.dbsp.sqlCompiler.CompilerMain.run(CompilerMain.java:139)
	at org.dbsp.sqlCompiler.CompilerMain.execute(CompilerMain.java:177)
	at org.dbsp.sqlCompiler.CompilerMain.main(CompilerMain.java:181)
```

**Comment by mihaibudiu** [comment]
I don't know where you found this error, the spew from Earth is never ending.
I thought I was testing all the projects. Maybe I am using the wrong compiler flags in my tests.

**Comment by mihaibudiu** [comment]
I tried to convert this PR to a draft, but the button does not seem to do anything. This won't work until the Rust code feeds data differently to tables with primary keys. (We could add yet another compiler flag to disable this behavior.)

**Review by ryzhyk — APPROVED** [review]

**Pull request merged**
