### PR TITLE
Add option to configure circular buffer threshold when parsing Change Stream 

### PR DESCRIPTION
**Pull request by Karakatiza666**
Improve look and padding around split pane resizers

Set a limit of 10 MiB which fits a couple batches of JSON from pipeline with a high throughput. Easily configurable hardcoded value.

### CODE REVIEW

**Comment by gz** [comment]
can you tell me what I should test?

**Comment by Karakatiza666** [comment]
The only way to easily see number of skipped bytes is via console log.
I just added that to easily observe skipped bytes.

You could test it with e.g. this program:

Look for `Skipped N of change stream. New buffer size is M` messages in browser console

```
-- Credit card holders.
CREATE TABLE CUSTOMER (
    cc_num BIGINT NOT NULL PRIMARY KEY, -- Credit card number
    name varchar,                       -- Customer name
    lat DOUBLE,                         -- Customer home address latitude
    long DOUBLE                         -- Customer home address longitude
) WITH (
    'materialized' = 'true',
    -- Configure the random data generator to generate 100000 customer records.
    -- (see https://www.feldera.com/docs/connectors/sources/datagen)
    'connectors' = '[{
      "transport": {
        "name": "datagen",
        "config": {
          "plan": [{
            "limit": 100000,
            "fields": {
              "name": { "strategy": "name" },
              "cc_num": { "range": [ 100000000000000, 100000000100000 ] },
              "lat": { "strategy": "uniform", "range": [ 25, 50 ] },
              "long": { "strategy": "uniform", "range": [ -126, -67 ] }
            }
          }]
        }
      }
    }]'
);

-- Credit card transactions.
CREATE TABLE TRANSACTION (
    ts TIMESTAMP LATENESS INTERVAL 10 MINUTES, -- Transaction time
    amt DOUBLE,                                -- Transaction amount
    cc_num BIGINT NOT NULL,                    -- Credit card number
    shipping_lat DOUBLE,                       -- Shipping address latitude
    shipping_long DOUBLE,                      -- Shipping address longitude
    FOREIGN KEY (cc_num) REFERENCES CUSTOMER(cc_num)
) WITH (
    'materialized' = 'true',
    -- Configure the random data generator to generate 1M transactions at the rate of 1000 transactions/s.
    'connectors' = '[{
      "transport": {
      "name": "datagen",
        "config": {
          "plan": [{
            "limit": 100000000,
            "rate": 100000,
            "fields": {
              "ts": { "strategy": "increment", "scale": 1000, "range": [1722063600000,2226985200000] },
              "amt": { "strategy": "zipf", "range": [ 1, 10000 ] },
              "cc_num": { "strategy": "uniform", "range": [ 100000000000000, 100000000100000 ] },
              "shipping_lat": { "strategy": "uniform", "range": [ 25, 50 ] },
              "shipping_long": { "strategy": "uniform", "range": [ -126, -67 ] }
            }
          }]
        }
      }
    }]'
);
 
-- Data enrichment query: left-join the TRANSACTION table with the CUSTOMER table to compute the
-- distance between the shipping address and the customer's home address for each transaction.
CREATE VIEW TRANSACTION_WITH_DISTANCE AS
    SELECT
        t.*,
        ST_DISTANCE(ST_POINT(shipping_long, shipping_lat), ST_POINT(long,lat)) AS distance
    FROM
        TRANSACTION as t
        LEFT JOIN CUSTOMER as c
        ON t.cc_num = c.cc_num;

-- Compute two rolling aggregates over a 1-day time window for each transaction:
-- 1. Average spend per transaction.
-- 2. The number of transactions whose shipping address is more than 50,000 meters away from
--    the card holder's home address.
CREATE VIEW TRANSACTION_WITH_AGGREGATES AS
SELECT
   *,
   AVG(amt) OVER window_1_day as avg_1day,
   SUM(case when distance > 50000 then 1 else 0 end) OVER window_1_day as count_1day
FROM
  TRANSACTION_WITH_DISTANCE
WINDOW window_1_day AS (PARTITION BY cc_num ORDER BY ts RANGE BETWEEN INTERVAL 1 DAYS PRECEDING AND CURRENT ROW);
```

**Comment by gz** [comment]
looks good, but we need make it so it appears visible to a user instead of just in the browser console log (I don't think any user will ever look there)

Screenshot from 2024-08-27 12-46-02

e..g, can you make a banner that shows up at the very top of the changestream content that looks like this and says something like "High Load Detected: Some records were skipped to maintain browser performance" and make the banner always visible as while it scrolls the changes

Screenshot from 2024-08-27 12-53-12

**Review by gz — APPROVED** [review]

**Comment by mihaibudiu** [comment]
it's not clear when the banner should disappear
could have a counter with "skipped records", and also every time something is skipped an output line

**Comment by lalithsuresh** [comment]
Something like "We're getting changes faster than we can display here. Skipping some records to keep up."

**Comment by gz** [comment]
>it's not clear when the banner should disappear
once things are dropped, it should never disappear until pipeline is restarted

**Comment by gz** [comment]
> could have a counter with "skipped records", and also every time something is skipped an output line

I don't think giving an exact count is useful (what can a user do with the information) and currently not possible as discussed this morning just inform that things aren't complete

**Comment by Karakatiza666** [comment]
I can add such a notification no problemo, but do we really want it? It may confuse a user as to if anything is wrong, and as Leonid mentioned today, does the user really care untill they scroll up to see a point (row) that says the bytes were dropped?

I could also make it less intrusive, e.g. it's an orange warning circle first, and after you click/hover over it expands to reveal the warning message

**Comment by gz** [comment]
I think blocking the text of the change stream is kinda ugly/non-ergonomic..can'tit be a banner on top (can be very small) similar to this UX:



image

**Comment by Karakatiza666** [comment]
So this banner would be on top of change stream UI, right? So it would still take up a little vertical space, but at least symmetric?

**Comment by Karakatiza666** [comment]
image

**Pull request merged**
