### PR TITLE
Add 'Inspect connector' button to the connector list in Pipeline Builder

### PR DESCRIPTION
**Pull request by Karakatiza666**
Open modal popup with non-editable config of the connector
Fix https://github.com/feldera/feldera/issues/1089

Is this a user-visible change (yes/no): yes

### CODE REVIEW

**Comment by Karakatiza666** [comment]
image
image

**Comment by gz** [comment]
If I inspect the connector and then close it, I'm out of the connector list and have to select a type again:


[Screencast from 12-11-2023 12:22:40 PM.webm](https://github.com/feldera/feldera/assets/127654/c6614f46-9f6b-
4efb-9a5b-2ac4c6748b4e)


it should keep the list where I clicked the Inspect button open.

**Comment by gz** [comment]
there used to be icons here?

Screenshot from 2023-12-11 12-25-42

**Comment by gz** [comment]
I think the `>` should not appear as long as we havent selected a connector type (and have a table view) 


Screenshot from 2023-12-11 12-30-35

**Review by gz — APPROVED** [review]
lgtm aside from comments above

**Comment by gz** [comment]
> The icons missing (Firefox only) and drawer opening on reload is a regression from another commit.
do we have issues for it?

**Pull request merged**
