### PR TITLE
pipeline-manager: add a feature flag to disable static-site serving

### PR DESCRIPTION
**Pull request by lalithsuresh**
When using the pipeline-manager as a library, we don't necessarily need static site serving. This allows such projects to avoid having the web-console be involved in every build.

This commit was also done in response to a regression potentially introduced by 5bade13802c9f14ec44ed274fb4f78d405e1ee88, which causes the the pipeline manager build to break when used as a dependency. What seems to happen is that generated assets referred to by the following line in `api.rs`:

``` include!(concat!(env!("OUT_DIR"), "/generated.rs")); ```

...are no longer available on incremental rebuilds, presumably due to some misconfiguration in `build.rs`.

Is this a user-visible change (yes/no): no

### CODE REVIEW

**Comment by gz** [comment]
might be better to just add an env variable that modifies build.rs to generate an empty ResourceDir in build.rs if set (then code in pipeline manager stays unmodified, and no extra feature flag is necessary)

**Comment by lalithsuresh** [comment]
@gz even commenting out all of build.rs didn't fix the problem for me. The issue is somehow related to the static file magic in api.rs.

**Comment by gz** [comment]
> @gz even commenting out all of build.rs didn't fix the problem for me. The issue is somehow related to the static file magic in api.rs.

Yes I think commenting out won;t work but you can generate an empty ResourceDir instead of one based on `out` I can have a look later and submit a commit to this pR

**Comment by gz** [comment]
fwiw you should also be able to skip the build by setting WEBUI_BUILD_DIR=$some_empty_dir

**Comment by lalithsuresh** [comment]
@gz looks like this bug with the missing files happens even without using the pipeline manager as a dependency, which makes it clear that this is a pretty bad regression. I am unable to do `cargo run` back-to-back on the pipeline crate, so something is definitely broken with the web-console build.

**Pull request closed without merging**
