### PR TITLE
py: publish to pypi

### PR DESCRIPTION
**Pull request by abhizer**
Adds a github workflow for publishing to pypi.

Requires us to setup a Github Action Secret

Fixes: #2348

### CODE REVIEW

**Review by ryzhyk — APPROVED** [review]
Looks reasonable, but I have zero experience with this.

**Comment by gz** [comment]
Hi @abhizer lgtm but can we use uv instead of pip for managing the dependencies for the library: https://docs.astral.sh/uv/ it will make our life easier

**Comment by mihaibudiu** [comment]
we can use it, but we should not ask other people to use it.
we should ask them to use what everyone else does

**Comment by gz** [comment]
>we can use it, but we should not ask other people to use it.
> we should ask them to use what everyone else does

it is compatible with pip so someone can still use that. But turns out uv _is_ actually what all the hip python people use today

**Review by gz — APPROVED** [review]

**Review by snkas — APPROVED** [review]

**Comment by gz** [comment]
@abhizer can you make sure you add a few of us to the pypi library so we have some redundancy wrg to ownership? If we need to make an account etc. let us know what is required

**Pull request merged**
